version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.7
  github: haskell-works/github-release@1.3.3
  hackage: haskell-works/hackage@1.4.1
  merge-point: haskell-works/merge-point@1.0.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          write-result-workspace: true

      - merge-point/merge-point:
          name: Build Ok
          requires:
            - GHC 8.6.5

      - github/release-cabal:
          name: GitHub Release
          context: haskell-ci
          requires:
            - Build Ok
          attach-workspace: true
          source-env-file: ./build/project.env
          checkout: true
          before-release:
            - run:
                name: Prepare environment for release
                command: |
                  tar zcvf /tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz -C ./build/dist/ ./${BUILD_EXE_NAME}
          filters:
            branches:
              only: master

      # - hackage/upload:
      #     context: haskell-ci
      #     publish: true
      #     requires:
      #       - GitHub Release
