version: 2.1

orbs:
  haskell: haskell-works/haskell-build@1.6.6
  github: haskell-works/github-release@1.3.0
  hackage: haskell-works/hackage@1.1.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build:
          name: GHC 8.6.4
          executor: haskell/ghc-8_6_4
          write-result-workspace: true

      - github/release-cabal:
          context: haskell-ci
          name: GitHub Release
          attach-workspace: true
          source-env-file: ./build/project.env
          requires:
            - GHC 8.6.4
          checkout: true
          before-release:
            - run:
                name: Prepare environment for release
                command: |
                  tar zcvf /tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz -C ./build/dist/ ./${BUILD_EXE_NAME}
          filters:
            branches:
              only: master

      # - hackage/upload:
      #     context: haskell-ci
      #     publish: true
      #     requires:
      #       - GitHub Release
